name: Build and Deploy React (Vite)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@v4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.YOUR_HOSTINGER_USERNAME }}
          server-ip: ${{ secrets.YOUR_SERVER_IP }}
          remote-path: public_html
          local-path: dist/
